import Head from 'next/head'
import React from 'react'
import Footer from './Footer'
import Header from './Header'
import Hero from './hero'

function Layout({ title, children }) {
    return (
        <>
            <Head>
                <title>{title ? title + " - Paixão" : "Paixão"}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex flex-col justify-between min-h-screen'>
                <Header />
                <main className='m-auto mt-10 px-4'>
                    {children}
                </main>
                <Footer />
            </div>
        </>
    )
}

export default Layout