import Head from 'next/head'
import React from 'react'
import Login from './Login'

function Layout({ title, children }) {
    return (
        <>
            <Head>
                <title>{title ? title + " - koo" : "koo"}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Login className="cursor-pointer"></Login>
            </header>

            <main>
                {children}
            </main>

            <footer>
            </footer>
        </>
    )
}

export default Layout